"""Stations

Revision ID: 985738e37bdb
Revises: b533c33be802
Create Date: 2024-09-21 16:31:01.118960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import mapadroid

# revision identifiers, used by Alembic.
revision = '985738e37bdb'
down_revision = 'b533c33be802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
                    sa.Column('id', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
                    sa.Column('lat', sa.Double(asdecimal=True), nullable=False),
                    sa.Column('lon', sa.Double(asdecimal=True), nullable=False),
                    sa.Column('name', sa.String(length=128, collation='utf8mb4_unicode_ci'), nullable=False),
                    sa.Column('start_time', mapadroid.db.TZDateTime.TZDateTime(), nullable=False),
                    sa.Column('end_time', mapadroid.db.TZDateTime.TZDateTime(), nullable=False),
                    sa.Column('is_battle_available', sa.BOOLEAN(), nullable=False),
                    sa.Column('is_inactive', sa.BOOLEAN(), nullable=False),
                    sa.Column('battle_level', mysql.TINYINT(display_width=1, unsigned=True), nullable=True),
                    sa.Column('battle_spawn', mapadroid.db.TZDateTime.TZDateTime(), nullable=True),
                    sa.Column('battle_start', mapadroid.db.TZDateTime.TZDateTime(), nullable=True),
                    sa.Column('battle_end', mapadroid.db.TZDateTime.TZDateTime(), nullable=True),
                    sa.Column('battle_pokemon_id', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('battle_pokemon_form', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('battle_pokemon_costume', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('battle_pokemon_gender', mysql.TINYINT(display_width=1, unsigned=True), nullable=True),
                    sa.Column('battle_pokemon_alignment', mysql.SMALLINT(display_width=6, unsigned=True),
                              nullable=True),
                    sa.Column('battle_pokemon_bread_mode', mysql.SMALLINT(display_width=6, unsigned=True),
                              nullable=True),
                    sa.Column('battle_pokemon_move_1', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('battle_pokemon_move_2', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('reward_pokemon_id', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('reward_pokemon_form', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('reward_pokemon_costume', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('reward_pokemon_gender', mysql.TINYINT(display_width=1, unsigned=True), nullable=True),
                    sa.Column('reward_pokemon_alignment', mysql.SMALLINT(display_width=6, unsigned=True),
                              nullable=True),
                    sa.Column('reward_pokemon_bread_mode', mysql.SMALLINT(display_width=6, unsigned=True),
                              nullable=True),
                    sa.Column('total_stationed_pokemon', mysql.SMALLINT(display_width=6, unsigned=True), nullable=True),
                    sa.Column('updated', mapadroid.db.TZDateTime.TZDateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_station_battle_end'), 'station', ['battle_end'], unique=False)
    op.create_index(op.f('ix_station_battle_pokemon_id'), 'station', ['battle_pokemon_id'], unique=False)
    op.create_index(op.f('ix_station_end_time'), 'station', ['end_time'], unique=False)
    op.create_index(op.f('ix_station_updated'), 'station', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_updated'), table_name='station')
    op.drop_index(op.f('ix_station_end_time'), table_name='station')
    op.drop_index(op.f('ix_station_battle_pokemon_id'), table_name='station')
    op.drop_index(op.f('ix_station_battle_end'), table_name='station')
    op.drop_table('station')
    # ### end Alembic commands ###
